book_store_app/urls.py
from django.urls import path
from . import views

app_name = 'book_store_app'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('sing_up/', views.sing_up_view, name='sing_up'),
    path('login/', views.login_view, name='login'),
    path('client_index/', views.client_index_view, name='client_index'),
    path('client_profile/', views.client_profile_view, name='client_profile'),
    path('client_purchases_history/', views.client_purchases_history_view, name='client_purchases_history'),
    path('logout/', views.logout_view, name='logout'),
]

book_store_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('book_store_app.urls')),
    path('admin/', admin.site.urls),
]

book_store_app/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User


class BookModel(models.Model):
    title = models.CharField(max_length=100)
    editorial = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    year = models.DateField()
    edition = models.CharField(max_length=50)
    city = models.CharField(max_length=100)
    stock = models.IntegerField(default=1)
    price = models.FloatField(default=1)

    def __str__(self):
        return '%s' % self.title


class UserPurchaseHistoryModel(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    book = models.ForeignKey(
        BookModel,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    date = models.DateField(default=datetime.date.today)
    qty = models.IntegerField(blank=True, null=True, default=None)
    price = models.FloatField(blank=True, null=True, default=None)


class ProfileDataModel(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    country = models.CharField(max_length=250, blank=True, null=True, default=None)
    city = models.CharField(max_length=200, blank=True, null=True, default=None)
    address = models.CharField(max_length=250, blank=True, null=True, default=None)
    zip_or_postal_code = models.IntegerField(blank=True, null=True, default=None)
    phone = models.CharField(max_length=20, blank=True, null=True, default=None)
    book_coins = models.FloatField(default=20, blank=True, null=True)

    def __str__(self):
        return '%s' % self.user.username

book_store_app/forms.py
from book_store_app.models import ProfileDataModel
from django import forms
from django.forms import ModelForm


class SingUpForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    email = forms.CharField(label='Email', max_length=100)
    password = forms.CharField(label='password', max_length=50, widget=forms.PasswordInput)


class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password', max_length=50, widget=forms.PasswordInput)


class ProfileForm(ModelForm):
    first_name = forms.CharField(label='First name', max_length=100, required=False)
    last_name = forms.CharField(label='Last name', max_length=100, required=False)

    class Meta:
        model = ProfileDataModel
        fields = ['country', 'city', 'address', 'zip_or_postal_code', 'phone']

book_store_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import SingUpForm, LoginForm, ProfileForm
from .models import BookModel, ProfileDataModel, UserPurchaseHistoryModel
from django.shortcuts import render, redirect


def sing_up_view(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('admin:index')
        else:
            return redirect('book_store_app:client_index')

    if request.method == 'POST':
        form = SingUpForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'],
                                                form.cleaned_data['password'])
            ProfileDataModel.objects.create(user_id=new_user.id)
            return redirect('book_store_app:login')

    form = SingUpForm()
    return render(request, 'book_store_app/sing_up.html', {'form': form})


def login_view(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('admin:index')
        else:
            return redirect('book_store_app:client_index')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('book_store_app:client_index')

    form = LoginForm()
    return render(request, 'book_store_app/login.html', {'form': form})


@login_required(login_url='book_store_app:login')
def client_index_view(request):
    if request.user.is_staff:
        return redirect('admin:index')
    books = BookModel.objects.all()
    book_coins = request.user.profiledatamodel.book_coins
    return render(request, 'book_store_app/client_index.html', {'books': books, 'book_coins': book_coins})


@login_required(login_url='book_store_app:login')
def client_profile_view(request):
    if request.user.is_staff:
        return redirect('admin:index')

    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            request.user.first_name = form.cleaned_data['first_name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.save()

            request.user.profiledatamodel.country = form.cleaned_data['country']
            request.user.profiledatamodel.city = form.cleaned_data['city']
            request.user.profiledatamodel.address = form.cleaned_data['address']
            request.user.profiledatamodel.zip_or_postal_code = form.cleaned_data['zip_or_postal_code']
            request.user.profiledatamodel.phone = form.cleaned_data['phone']
            request.user.profiledatamodel.save()

            return render(request, 'book_store_app/client_profile.html', {'profile_form': form})

    user_profile_data = {'first_name': request.user.first_name,
                         'last_name': request.user.last_name,
                         'country': request.user.profiledatamodel.country,
                         'city': request.user.profiledatamodel.city,
                         'address': request.user.profiledatamodel.address,
                         'zip_or_postal_code': request.user.profiledatamodel.zip_or_postal_code,
                         'phone': request.user.profiledatamodel.phone}
    profile_form = ProfileForm(user_profile_data)

    return render(request, 'book_store_app/client_profile.html', {'profile_form': profile_form})


@login_required(login_url='book_store_app:login')
def client_purchases_history_view(request):
    if request.user.is_staff:
        return redirect('admin:index')
    if (request.user.first_name is None or
            request.user.last_name is None or
            request.user.profiledatamodel.city is None or
            request.user.profiledatamodel.address is None or
            request.user.profiledatamodel.phone is None or
            request.user.profiledatamodel.zip_or_postal_code is None or
            request.user.profiledatamodel.country is None):
        return redirect('book_store_app:client_profile')

    status = ''
    if request.method == 'POST':
        book = BookModel.objects.get(pk=request.POST['book_id'])
        book_qty_asked = float(request.POST['book_qty'])
        total_price = book_qty_asked * book.price
        if book.stock >= book_qty_asked and request.user.profiledatamodel.book_coins >= total_price:
            new_purchase = UserPurchaseHistoryModel.objects.create(user_id=request.user.id)
            new_purchase.book = book
            new_purchase.save()

            new_purchase.price = total_price
            new_purchase.qty = book_qty_asked
            new_purchase.save()

            request.user.profiledatamodel.book_coins -= total_price
            request.user.profiledatamodel.save()

            book.stock -= book_qty_asked
            book.save()
            status = 'Purchase completed'
        else:
            status = 'Something went wrong'
    purchased_books = UserPurchaseHistoryModel.objects.filter(user_id=request.user.id)
    return render(request, 'book_store_app/purchase_history.html',
                  {'status': status, 'purchased_books': purchased_books})


def logout_view(request):
    logout(request)
    return redirect('book_store_app:login')


def index_view(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('admin:index')
        else:
            return redirect('book_store_app:client_index')
    return render(request, 'book_store_app/index.html')

book_store_app/templates/book_store_app/client_base.html
{% extends 'book_store_app/import_base.html' %}
{% block body %}
    {% block banner %}
        <nav class="navbar navbar-dark bg-primary">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                    aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'book_store_app:client_index' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book_store_app:client_profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book_store_app:client_purchases_history' %}">Purchases history</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book_store_app:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
    {% endblock %}
    {% block content %}{% endblock %}
{% endblock %}

book_store_app/templates/book_store_app/client_index.html
{% extends 'book_store_app/client_base.html' %}

{% block content %}
    Book Coins: {{ book_coins }}
    <table class="table">
        <thead>
        <tr>
            <td>Title</td>
            <td>Author</td>
            <td>Year</td>
            <td>Edition</td>
            <td>Editorial</td>
            <td>City</td>
            <td>Price</td>
            <td>Qty</td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            {% if book.stock >= 1 %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.year }}</td>
                    <td>{{ book.edition }}</td>
                    <td>{{ book.editorial }}</td>
                    <td>{{ book.city }}</td>
                    <td>{{ book.price }}</td>
                    <form method="post" action="{% url 'book_store_app:client_purchases_history' %}">
                        {% csrf_token %}
                        <input name="book_id" type="hidden" value={{ book.id }}>
                        <td> <input name="book_qty" type="number" value="1" min="1" max="{{ book.stock }}"> </td>
                        <td><input type="submit" onclick="buy_book_clicked(event)" class="btn btn-primary" value="buy" ></td>
                    </form>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

<script>
    function buy_book_clicked(e) {
        if(!confirm('Are you sure?')){
            e.preventDefault()
        }
    }
</script>
{% endblock %}

book_store_app/templates/book_store_app/client_profile.html
{% extends 'book_store_app/client_base.html' %}

{% block content %}
    {% load crispy_forms_tags %}
    <form action="{% url 'book_store_app:client_profile' %}" method="post">
        {% csrf_token %}
        {{ profile_form|crispy }}
        <input type="submit" value="Submit" class="btn-primary btn">
    </form>
{% endblock %}

book_store_app/templates/book_store_app/import_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
    {% endblock %}
    <title>Book Store</title>
</head>
<body>
<div class="container-fluid pt-3">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

book_store_app/templates/book_store_app/index.html
{% extends 'book_store_app/import_base.html' %}
{% block body %}
    <a href="{% url 'book_store_app:sing_up' %}">Sing up</a>
    <br>
    <a href="{% url 'book_store_app:login' %}">Login</a>
{% endblock %}

book_store_app/templates/book_store_app/login.html
{% extends 'book_store_app/import_base.html' %}
{% block body %}
    <a href="{% url 'book_store_app:index' %}">Return</a>
    {% load crispy_forms_tags %}
    <form action="{% url 'book_store_app:login' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn-primary btn">
    </form>
{% endblock %}

book_store_app/templates/book_store_app/purchase_history.html
{% extends 'book_store_app/client_base.html' %}

{% block content %}
    {% firstof status %}
    <table class="table">
        <thead>
        <tr>
            <td>Title</td>
            <td>Author</td>
            <td>Year</td>
            <td>Edition</td>
            <td>Editorial</td>
            <td>City</td>
            <td>Price</td>
            <td>Qty</td>
            <td>Date</td>
        </tr>
        </thead>
        <tbody>
        {% for purchased_book in purchased_books %}
            <tr>
                <td>{{ purchased_book.book.title }}</td>
                <td>{{ purchased_book.book.author }}</td>
                <td>{{ purchased_book.book.year }}</td>
                <td>{{ purchased_book.book.edition }}</td>
                <td>{{ purchased_book.book.editorial }}</td>
                <td>{{ purchased_book.book.city }}</td>
                <td>{{ purchased_book.price }}</td>
                <td>{{ purchased_book.qty }}</td>
                <td>{{ purchased_book.date }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

book_store_app/templates/book_store_app/sing_up.html
{% extends 'book_store_app/import_base.html' %}
{% block body %}
<a href="{% url 'book_store_app:index' %}">Return</a>
<form action="{% url 'book_store_app:sing_up' %}" method="post" class="form-group">
    {% load crispy_forms_tags %}
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}